/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AppRouteImport } from './routes/app'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as VerifyKeyRouteImport } from './routes/verify.$key'
import { Route as CoinIdRouteImport } from './routes/coin.$id'
import { Route as AssetAssetIdRouteImport } from './routes/asset.$assetId'
import { Route as AppTopupRouteImport } from './routes/app.topup'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppPublishRouteImport } from './routes/app.publish'
import { Route as AppLookupRouteImport } from './routes/app.lookup'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SitePersonalRouteImport } from './routes/_site.personal'
import { Route as SiteManifestoRouteImport } from './routes/_site.manifesto'
import { Route as SiteLearnMoreRouteImport } from './routes/_site.learn-more'
import { Route as SiteHelpRouteImport } from './routes/_site.help'
import { Route as SiteBusinessRouteImport } from './routes/_site.business'
import { Route as SiteAndroidRouteImport } from './routes/_site.android'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteVerifyIndexRouteImport } from './routes/_site.verify.index'
import { Route as AppCoinIdRouteImport } from './routes/app.coin.$id'
import { Route as AppAssetAssetIdRouteImport } from './routes/app.asset.$assetId'
import { Route as ApiPublicLatestReleaseRouteImport } from './routes/api/public/latest-release'
import { Route as ApiPublicApkRouteImport } from './routes/api/public/apk'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AppVerifyChainAddressRouteImport } from './routes/app.verify.$chain.$address'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksWatchTickRouteImport } from './routes/api/public/hooks/watch-tick'
import { Route as ApiPublicHooksPublishReleaseRouteImport } from './routes/api/public/hooks/publish-release'
import { Route as ApiPublicCronHouseBalanceRouteImport } from './routes/api/public/cron/house-balance'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const VerifyKeyRoute = VerifyKeyRouteImport.update({
  id: '/verify/$key',
  path: '/verify/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinIdRoute = CoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetAssetIdRoute = AssetAssetIdRouteImport.update({
  id: '/asset/$assetId',
  path: '/asset/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopupRoute = AppTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppLookupRoute = AppLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SitePersonalRoute = SitePersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => SiteRoute,
} as any)
const SiteManifestoRoute = SiteManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLearnMoreRoute = SiteLearnMoreRouteImport.update({
  id: '/learn-more',
  path: '/learn-more',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHelpRoute = SiteHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBusinessRoute = SiteBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAndroidRoute = SiteAndroidRouteImport.update({
  id: '/android',
  path: '/android',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVerifyIndexRoute = SiteVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => SiteRoute,
} as any)
const AppCoinIdRoute = AppCoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetAssetIdRoute = AppAssetAssetIdRouteImport.update({
  id: '/asset/$assetId',
  path: '/asset/$assetId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicLatestReleaseRoute = ApiPublicLatestReleaseRouteImport.update({
  id: '/api/public/latest-release',
  path: '/api/public/latest-release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApkRoute = ApiPublicApkRouteImport.update({
  id: '/api/public/apk',
  path: '/api/public/apk',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifyChainAddressRoute = AppVerifyChainAddressRouteImport.update({
  id: '/verify/$chain/$address',
  path: '/verify/$chain/$address',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWatchTickRoute = ApiPublicHooksWatchTickRouteImport.update({
  id: '/api/public/hooks/watch-tick',
  path: '/api/public/hooks/watch-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPublishReleaseRoute =
  ApiPublicHooksPublishReleaseRouteImport.update({
    id: '/api/public/hooks/publish-release',
    path: '/api/public/hooks/publish-release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronHouseBalanceRoute =
  ApiPublicCronHouseBalanceRouteImport.update({
    id: '/api/public/cron/house-balance',
    path: '/api/public/cron/house-balance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRouteWithChildren
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/handoff': typeof HandoffRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/lookup': typeof LookupRoute
  '/publish': typeof PublishRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/topup': typeof TopupRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof SiteAboutRoute
  '/android': typeof SiteAndroidRoute
  '/business': typeof SiteBusinessRoute
  '/help': typeof SiteHelpRoute
  '/learn-more': typeof SiteLearnMoreRoute
  '/manifesto': typeof SiteManifestoRoute
  '/personal': typeof SitePersonalRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/home': typeof AppHomeRoute
  '/app/import': typeof AppImportRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/publish': typeof AppPublishRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/topup': typeof AppTopupRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/coin/$id': typeof CoinIdRoute
  '/verify/$key': typeof VerifyKeyRoute
  '/app/': typeof AppIndexRoute
  '/api/public/apk': typeof ApiPublicApkRoute
  '/api/public/latest-release': typeof ApiPublicLatestReleaseRoute
  '/app/asset/$assetId': typeof AppAssetAssetIdRoute
  '/app/coin/$id': typeof AppCoinIdRoute
  '/verify/': typeof SiteVerifyIndexRoute
  '/api/public/cron/house-balance': typeof ApiPublicCronHouseBalanceRoute
  '/api/public/hooks/publish-release': typeof ApiPublicHooksPublishReleaseRoute
  '/api/public/hooks/watch-tick': typeof ApiPublicHooksWatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/verify/$chain/$address': typeof AppVerifyChainAddressRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/handoff': typeof HandoffRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/lookup': typeof LookupRoute
  '/publish': typeof PublishRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/topup': typeof TopupRoute
  '/welcome': typeof WelcomeRoute
  '/about': typeof SiteAboutRoute
  '/android': typeof SiteAndroidRoute
  '/business': typeof SiteBusinessRoute
  '/help': typeof SiteHelpRoute
  '/learn-more': typeof SiteLearnMoreRoute
  '/manifesto': typeof SiteManifestoRoute
  '/personal': typeof SitePersonalRoute
  '/privacy': typeof SitePrivacyRoute
  '/terms': typeof SiteTermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/home': typeof AppHomeRoute
  '/app/import': typeof AppImportRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/publish': typeof AppPublishRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/topup': typeof AppTopupRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/coin/$id': typeof CoinIdRoute
  '/verify/$key': typeof VerifyKeyRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/apk': typeof ApiPublicApkRoute
  '/api/public/latest-release': typeof ApiPublicLatestReleaseRoute
  '/app/asset/$assetId': typeof AppAssetAssetIdRoute
  '/app/coin/$id': typeof AppCoinIdRoute
  '/verify': typeof SiteVerifyIndexRoute
  '/api/public/cron/house-balance': typeof ApiPublicCronHouseBalanceRoute
  '/api/public/hooks/publish-release': typeof ApiPublicHooksPublishReleaseRoute
  '/api/public/hooks/watch-tick': typeof ApiPublicHooksWatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/verify/$chain/$address': typeof AppVerifyChainAddressRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/app': typeof AppRouteWithChildren
  '/assets': typeof AssetsRoute
  '/auth': typeof AuthRoute
  '/handoff': typeof HandoffRoute
  '/home': typeof HomeRoute
  '/import': typeof ImportRoute
  '/lookup': typeof LookupRoute
  '/publish': typeof PublishRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/topup': typeof TopupRoute
  '/welcome': typeof WelcomeRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/android': typeof SiteAndroidRoute
  '/_site/business': typeof SiteBusinessRoute
  '/_site/help': typeof SiteHelpRoute
  '/_site/learn-more': typeof SiteLearnMoreRoute
  '/_site/manifesto': typeof SiteManifestoRoute
  '/_site/personal': typeof SitePersonalRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/terms': typeof SiteTermsRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/home': typeof AppHomeRoute
  '/app/import': typeof AppImportRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/publish': typeof AppPublishRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/topup': typeof AppTopupRoute
  '/asset/$assetId': typeof AssetAssetIdRoute
  '/coin/$id': typeof CoinIdRoute
  '/verify/$key': typeof VerifyKeyRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/apk': typeof ApiPublicApkRoute
  '/api/public/latest-release': typeof ApiPublicLatestReleaseRoute
  '/app/asset/$assetId': typeof AppAssetAssetIdRoute
  '/app/coin/$id': typeof AppCoinIdRoute
  '/_site/verify/': typeof SiteVerifyIndexRoute
  '/api/public/cron/house-balance': typeof ApiPublicCronHouseBalanceRoute
  '/api/public/hooks/publish-release': typeof ApiPublicHooksPublishReleaseRoute
  '/api/public/hooks/watch-tick': typeof ApiPublicHooksWatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/verify/$chain/$address': typeof AppVerifyChainAddressRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/app'
    | '/assets'
    | '/auth'
    | '/handoff'
    | '/home'
    | '/import'
    | '/lookup'
    | '/publish'
    | '/recover'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/topup'
    | '/welcome'
    | '/about'
    | '/android'
    | '/business'
    | '/help'
    | '/learn-more'
    | '/manifesto'
    | '/personal'
    | '/privacy'
    | '/terms'
    | '/app/admin'
    | '/app/alerts'
    | '/app/assets'
    | '/app/home'
    | '/app/import'
    | '/app/lookup'
    | '/app/publish'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/topup'
    | '/asset/$assetId'
    | '/coin/$id'
    | '/verify/$key'
    | '/app/'
    | '/api/public/apk'
    | '/api/public/latest-release'
    | '/app/asset/$assetId'
    | '/app/coin/$id'
    | '/verify/'
    | '/api/public/cron/house-balance'
    | '/api/public/hooks/publish-release'
    | '/api/public/hooks/watch-tick'
    | '/api/public/payments/webhook'
    | '/app/verify/$chain/$address'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/alerts'
    | '/assets'
    | '/auth'
    | '/handoff'
    | '/home'
    | '/import'
    | '/lookup'
    | '/publish'
    | '/recover'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/topup'
    | '/welcome'
    | '/about'
    | '/android'
    | '/business'
    | '/help'
    | '/learn-more'
    | '/manifesto'
    | '/personal'
    | '/privacy'
    | '/terms'
    | '/app/admin'
    | '/app/alerts'
    | '/app/assets'
    | '/app/home'
    | '/app/import'
    | '/app/lookup'
    | '/app/publish'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/topup'
    | '/asset/$assetId'
    | '/coin/$id'
    | '/verify/$key'
    | '/'
    | '/app'
    | '/api/public/apk'
    | '/api/public/latest-release'
    | '/app/asset/$assetId'
    | '/app/coin/$id'
    | '/verify'
    | '/api/public/cron/house-balance'
    | '/api/public/hooks/publish-release'
    | '/api/public/hooks/watch-tick'
    | '/api/public/payments/webhook'
    | '/app/verify/$chain/$address'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/alerts'
    | '/app'
    | '/assets'
    | '/auth'
    | '/handoff'
    | '/home'
    | '/import'
    | '/lookup'
    | '/publish'
    | '/recover'
    | '/reset-password'
    | '/scan'
    | '/settings'
    | '/shop'
    | '/topup'
    | '/welcome'
    | '/_site/about'
    | '/_site/android'
    | '/_site/business'
    | '/_site/help'
    | '/_site/learn-more'
    | '/_site/manifesto'
    | '/_site/personal'
    | '/_site/privacy'
    | '/_site/terms'
    | '/app/admin'
    | '/app/alerts'
    | '/app/assets'
    | '/app/home'
    | '/app/import'
    | '/app/lookup'
    | '/app/publish'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/topup'
    | '/asset/$assetId'
    | '/coin/$id'
    | '/verify/$key'
    | '/_site/'
    | '/app/'
    | '/api/public/apk'
    | '/api/public/latest-release'
    | '/app/asset/$assetId'
    | '/app/coin/$id'
    | '/_site/verify/'
    | '/api/public/cron/house-balance'
    | '/api/public/hooks/publish-release'
    | '/api/public/hooks/watch-tick'
    | '/api/public/payments/webhook'
    | '/app/verify/$chain/$address'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AppRoute: typeof AppRouteWithChildren
  AssetsRoute: typeof AssetsRoute
  AuthRoute: typeof AuthRoute
  HandoffRoute: typeof HandoffRoute
  HomeRoute: typeof HomeRoute
  ImportRoute: typeof ImportRoute
  LookupRoute: typeof LookupRoute
  PublishRoute: typeof PublishRoute
  RecoverRoute: typeof RecoverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  TopupRoute: typeof TopupRoute
  WelcomeRoute: typeof WelcomeRoute
  AssetAssetIdRoute: typeof AssetAssetIdRoute
  CoinIdRoute: typeof CoinIdRoute
  VerifyKeyRoute: typeof VerifyKeyRoute
  ApiPublicApkRoute: typeof ApiPublicApkRoute
  ApiPublicLatestReleaseRoute: typeof ApiPublicLatestReleaseRoute
  ApiPublicCronHouseBalanceRoute: typeof ApiPublicCronHouseBalanceRoute
  ApiPublicHooksPublishReleaseRoute: typeof ApiPublicHooksPublishReleaseRoute
  ApiPublicHooksWatchTickRoute: typeof ApiPublicHooksWatchTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/verify/$key': {
      id: '/verify/$key'
      path: '/verify/$key'
      fullPath: '/verify/$key'
      preLoaderRoute: typeof VerifyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$id': {
      id: '/coin/$id'
      path: '/coin/$id'
      fullPath: '/coin/$id'
      preLoaderRoute: typeof CoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$assetId': {
      id: '/asset/$assetId'
      path: '/asset/$assetId'
      fullPath: '/asset/$assetId'
      preLoaderRoute: typeof AssetAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/topup': {
      id: '/app/topup'
      path: '/topup'
      fullPath: '/app/topup'
      preLoaderRoute: typeof AppTopupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lookup': {
      id: '/app/lookup'
      path: '/lookup'
      fullPath: '/app/lookup'
      preLoaderRoute: typeof AppLookupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/personal': {
      id: '/_site/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof SitePersonalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/manifesto': {
      id: '/_site/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof SiteManifestoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/learn-more': {
      id: '/_site/learn-more'
      path: '/learn-more'
      fullPath: '/learn-more'
      preLoaderRoute: typeof SiteLearnMoreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/help': {
      id: '/_site/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof SiteHelpRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/business': {
      id: '/_site/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof SiteBusinessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/android': {
      id: '/_site/android'
      path: '/android'
      fullPath: '/android'
      preLoaderRoute: typeof SiteAndroidRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/verify/': {
      id: '/_site/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof SiteVerifyIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/coin/$id': {
      id: '/app/coin/$id'
      path: '/coin/$id'
      fullPath: '/app/coin/$id'
      preLoaderRoute: typeof AppCoinIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/asset/$assetId': {
      id: '/app/asset/$assetId'
      path: '/asset/$assetId'
      fullPath: '/app/asset/$assetId'
      preLoaderRoute: typeof AppAssetAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/latest-release': {
      id: '/api/public/latest-release'
      path: '/api/public/latest-release'
      fullPath: '/api/public/latest-release'
      preLoaderRoute: typeof ApiPublicLatestReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/apk': {
      id: '/api/public/apk'
      path: '/api/public/apk'
      fullPath: '/api/public/apk'
      preLoaderRoute: typeof ApiPublicApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/verify/$chain/$address': {
      id: '/app/verify/$chain/$address'
      path: '/verify/$chain/$address'
      fullPath: '/app/verify/$chain/$address'
      preLoaderRoute: typeof AppVerifyChainAddressRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/watch-tick': {
      id: '/api/public/hooks/watch-tick'
      path: '/api/public/hooks/watch-tick'
      fullPath: '/api/public/hooks/watch-tick'
      preLoaderRoute: typeof ApiPublicHooksWatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/publish-release': {
      id: '/api/public/hooks/publish-release'
      path: '/api/public/hooks/publish-release'
      fullPath: '/api/public/hooks/publish-release'
      preLoaderRoute: typeof ApiPublicHooksPublishReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/house-balance': {
      id: '/api/public/cron/house-balance'
      path: '/api/public/cron/house-balance'
      fullPath: '/api/public/cron/house-balance'
      preLoaderRoute: typeof ApiPublicCronHouseBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAndroidRoute: typeof SiteAndroidRoute
  SiteBusinessRoute: typeof SiteBusinessRoute
  SiteHelpRoute: typeof SiteHelpRoute
  SiteLearnMoreRoute: typeof SiteLearnMoreRoute
  SiteManifestoRoute: typeof SiteManifestoRoute
  SitePersonalRoute: typeof SitePersonalRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteVerifyIndexRoute: typeof SiteVerifyIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAndroidRoute: SiteAndroidRoute,
  SiteBusinessRoute: SiteBusinessRoute,
  SiteHelpRoute: SiteHelpRoute,
  SiteLearnMoreRoute: SiteLearnMoreRoute,
  SiteManifestoRoute: SiteManifestoRoute,
  SitePersonalRoute: SitePersonalRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteVerifyIndexRoute: SiteVerifyIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppImportRoute: typeof AppImportRoute
  AppLookupRoute: typeof AppLookupRoute
  AppPublishRoute: typeof AppPublishRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppTopupRoute: typeof AppTopupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssetAssetIdRoute: typeof AppAssetAssetIdRoute
  AppCoinIdRoute: typeof AppCoinIdRoute
  AppVerifyChainAddressRoute: typeof AppVerifyChainAddressRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppHomeRoute: AppHomeRoute,
  AppImportRoute: AppImportRoute,
  AppLookupRoute: AppLookupRoute,
  AppPublishRoute: AppPublishRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppTopupRoute: AppTopupRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssetAssetIdRoute: AppAssetAssetIdRoute,
  AppCoinIdRoute: AppCoinIdRoute,
  AppVerifyChainAddressRoute: AppVerifyChainAddressRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AppRoute: AppRouteWithChildren,
  AssetsRoute: AssetsRoute,
  AuthRoute: AuthRoute,
  HandoffRoute: HandoffRoute,
  HomeRoute: HomeRoute,
  ImportRoute: ImportRoute,
  LookupRoute: LookupRoute,
  PublishRoute: PublishRoute,
  RecoverRoute: RecoverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  TopupRoute: TopupRoute,
  WelcomeRoute: WelcomeRoute,
  AssetAssetIdRoute: AssetAssetIdRoute,
  CoinIdRoute: CoinIdRoute,
  VerifyKeyRoute: VerifyKeyRoute,
  ApiPublicApkRoute: ApiPublicApkRoute,
  ApiPublicLatestReleaseRoute: ApiPublicLatestReleaseRoute,
  ApiPublicCronHouseBalanceRoute: ApiPublicCronHouseBalanceRoute,
  ApiPublicHooksPublishReleaseRoute: ApiPublicHooksPublishReleaseRoute,
  ApiPublicHooksWatchTickRoute: ApiPublicHooksWatchTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
