/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyKeyRouteImport } from './routes/verify.$key'
import { Route as AppTopupRouteImport } from './routes/app.topup'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppPublishRouteImport } from './routes/app.publish'
import { Route as AppLookupRouteImport } from './routes/app.lookup'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppAssetsRouteImport } from './routes/app.assets'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppCoinIdRouteImport } from './routes/app.coin.$id'
import { Route as AppAssetAssetIdRouteImport } from './routes/app.asset.$assetId'
import { Route as AppVerifyChainAddressRouteImport } from './routes/app.verify.$chain.$address'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksWatchTickRouteImport } from './routes/api/public/hooks/watch-tick'
import { Route as ApiPublicCronHouseBalanceRouteImport } from './routes/api/public/cron/house-balance'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyKeyRoute = VerifyKeyRouteImport.update({
  id: '/verify/$key',
  path: '/verify/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopupRoute = AppTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppPublishRoute = AppPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AppRoute,
} as any)
const AppLookupRoute = AppLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCoinIdRoute = AppCoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetAssetIdRoute = AppAssetAssetIdRouteImport.update({
  id: '/asset/$assetId',
  path: '/asset/$assetId',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyChainAddressRoute = AppVerifyChainAddressRouteImport.update({
  id: '/verify/$chain/$address',
  path: '/verify/$chain/$address',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWatchTickRoute = ApiPublicHooksWatchTickRouteImport.update({
  id: '/api/public/hooks/watch-tick',
  path: '/api/public/hooks/watch-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronHouseBalanceRoute =
  ApiPublicCronHouseBalanceRouteImport.update({
    id: '/api/public/cron/house-balance',
    path: '/api/public/cron/house-balance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/handoff': typeof HandoffRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/home': typeof AppHomeRoute
  '/app/import': typeof AppImportRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/publish': typeof AppPublishRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/topup': typeof AppTopupRoute
  '/verify/$key': typeof VerifyKeyRoute
  '/app/asset/$assetId': typeof AppAssetAssetIdRoute
  '/app/coin/$id': typeof AppCoinIdRoute
  '/api/public/cron/house-balance': typeof ApiPublicCronHouseBalanceRoute
  '/api/public/hooks/watch-tick': typeof ApiPublicHooksWatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/verify/$chain/$address': typeof AppVerifyChainAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/handoff': typeof HandoffRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/home': typeof AppHomeRoute
  '/app/import': typeof AppImportRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/publish': typeof AppPublishRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/topup': typeof AppTopupRoute
  '/verify/$key': typeof VerifyKeyRoute
  '/app/asset/$assetId': typeof AppAssetAssetIdRoute
  '/app/coin/$id': typeof AppCoinIdRoute
  '/api/public/cron/house-balance': typeof ApiPublicCronHouseBalanceRoute
  '/api/public/hooks/watch-tick': typeof ApiPublicHooksWatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/verify/$chain/$address': typeof AppVerifyChainAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/handoff': typeof HandoffRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assets': typeof AppAssetsRoute
  '/app/home': typeof AppHomeRoute
  '/app/import': typeof AppImportRoute
  '/app/lookup': typeof AppLookupRoute
  '/app/publish': typeof AppPublishRoute
  '/app/scan': typeof AppScanRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shop': typeof AppShopRoute
  '/app/topup': typeof AppTopupRoute
  '/verify/$key': typeof VerifyKeyRoute
  '/app/asset/$assetId': typeof AppAssetAssetIdRoute
  '/app/coin/$id': typeof AppCoinIdRoute
  '/api/public/cron/house-balance': typeof ApiPublicCronHouseBalanceRoute
  '/api/public/hooks/watch-tick': typeof ApiPublicHooksWatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/verify/$chain/$address': typeof AppVerifyChainAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/handoff'
    | '/manifesto'
    | '/privacy'
    | '/recover'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/app/admin'
    | '/app/alerts'
    | '/app/assets'
    | '/app/home'
    | '/app/import'
    | '/app/lookup'
    | '/app/publish'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/topup'
    | '/verify/$key'
    | '/app/asset/$assetId'
    | '/app/coin/$id'
    | '/api/public/cron/house-balance'
    | '/api/public/hooks/watch-tick'
    | '/api/public/payments/webhook'
    | '/app/verify/$chain/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/handoff'
    | '/manifesto'
    | '/privacy'
    | '/recover'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/app/admin'
    | '/app/alerts'
    | '/app/assets'
    | '/app/home'
    | '/app/import'
    | '/app/lookup'
    | '/app/publish'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/topup'
    | '/verify/$key'
    | '/app/asset/$assetId'
    | '/app/coin/$id'
    | '/api/public/cron/house-balance'
    | '/api/public/hooks/watch-tick'
    | '/api/public/payments/webhook'
    | '/app/verify/$chain/$address'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/handoff'
    | '/manifesto'
    | '/privacy'
    | '/recover'
    | '/reset-password'
    | '/terms'
    | '/welcome'
    | '/app/admin'
    | '/app/alerts'
    | '/app/assets'
    | '/app/home'
    | '/app/import'
    | '/app/lookup'
    | '/app/publish'
    | '/app/scan'
    | '/app/settings'
    | '/app/shop'
    | '/app/topup'
    | '/verify/$key'
    | '/app/asset/$assetId'
    | '/app/coin/$id'
    | '/api/public/cron/house-balance'
    | '/api/public/hooks/watch-tick'
    | '/api/public/payments/webhook'
    | '/app/verify/$chain/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  HandoffRoute: typeof HandoffRoute
  ManifestoRoute: typeof ManifestoRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverRoute: typeof RecoverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  VerifyKeyRoute: typeof VerifyKeyRoute
  ApiPublicCronHouseBalanceRoute: typeof ApiPublicCronHouseBalanceRoute
  ApiPublicHooksWatchTickRoute: typeof ApiPublicHooksWatchTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$key': {
      id: '/verify/$key'
      path: '/verify/$key'
      fullPath: '/verify/$key'
      preLoaderRoute: typeof VerifyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/topup': {
      id: '/app/topup'
      path: '/topup'
      fullPath: '/app/topup'
      preLoaderRoute: typeof AppTopupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publish': {
      id: '/app/publish'
      path: '/publish'
      fullPath: '/app/publish'
      preLoaderRoute: typeof AppPublishRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lookup': {
      id: '/app/lookup'
      path: '/lookup'
      fullPath: '/app/lookup'
      preLoaderRoute: typeof AppLookupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assets': {
      id: '/app/assets'
      path: '/assets'
      fullPath: '/app/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coin/$id': {
      id: '/app/coin/$id'
      path: '/coin/$id'
      fullPath: '/app/coin/$id'
      preLoaderRoute: typeof AppCoinIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/asset/$assetId': {
      id: '/app/asset/$assetId'
      path: '/asset/$assetId'
      fullPath: '/app/asset/$assetId'
      preLoaderRoute: typeof AppAssetAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify/$chain/$address': {
      id: '/app/verify/$chain/$address'
      path: '/verify/$chain/$address'
      fullPath: '/app/verify/$chain/$address'
      preLoaderRoute: typeof AppVerifyChainAddressRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/watch-tick': {
      id: '/api/public/hooks/watch-tick'
      path: '/api/public/hooks/watch-tick'
      fullPath: '/api/public/hooks/watch-tick'
      preLoaderRoute: typeof ApiPublicHooksWatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/house-balance': {
      id: '/api/public/cron/house-balance'
      path: '/api/public/cron/house-balance'
      fullPath: '/api/public/cron/house-balance'
      preLoaderRoute: typeof ApiPublicCronHouseBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppAssetsRoute: typeof AppAssetsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppImportRoute: typeof AppImportRoute
  AppLookupRoute: typeof AppLookupRoute
  AppPublishRoute: typeof AppPublishRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopRoute: typeof AppShopRoute
  AppTopupRoute: typeof AppTopupRoute
  AppAssetAssetIdRoute: typeof AppAssetAssetIdRoute
  AppCoinIdRoute: typeof AppCoinIdRoute
  AppVerifyChainAddressRoute: typeof AppVerifyChainAddressRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppAssetsRoute: AppAssetsRoute,
  AppHomeRoute: AppHomeRoute,
  AppImportRoute: AppImportRoute,
  AppLookupRoute: AppLookupRoute,
  AppPublishRoute: AppPublishRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopRoute: AppShopRoute,
  AppTopupRoute: AppTopupRoute,
  AppAssetAssetIdRoute: AppAssetAssetIdRoute,
  AppCoinIdRoute: AppCoinIdRoute,
  AppVerifyChainAddressRoute: AppVerifyChainAddressRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  HandoffRoute: HandoffRoute,
  ManifestoRoute: ManifestoRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverRoute: RecoverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  VerifyKeyRoute: VerifyKeyRoute,
  ApiPublicCronHouseBalanceRoute: ApiPublicCronHouseBalanceRoute,
  ApiPublicHooksWatchTickRoute: ApiPublicHooksWatchTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
